default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test: &test
  <<: *default
  database: db/test.sqlite3

cucumber:
  <<: *test
  
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: EuVou_production
  username: EuVou
  password: <%= ENV['EUVOU_DATABASE_PASSWORD'] %>
